name: Docker Build with Autoversion

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for autoversion

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: run it
        run: |
          go install github.com/trondhindenes/autoversion/cmd/autoversion@v1.0.23
          autoversion

      - name: run stuff
        run: |
          printenv
          git branch -a
          #git fetch
          #git branch -a
          #git checkout main

      - name: Calculate version
        id: version
        uses: trondhindenes/autoversion@v1.0.23

