name: Docker Build with Autoversion

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for autoversion

      - name: Calculate version
        id: version
        uses: trondhindenes/autoversion-action@v1

      - name: Use version outputs
        run: |
          echo "semver: ${{ steps.version.outputs.semver }}"
          echo "semverWithPrefix: ${{ steps.version.outputs.semverWithPrefix }}"
          echo "pep440: ${{ steps.version.outputs.pep440 }}"
          echo "pep440WithPrefix: ${{ steps.version.outputs.pep440WithPrefix }}"
          echo "major: ${{ steps.version.outputs.major }}"
          echo "minor: ${{ steps.version.outputs.minor }}"
          echo "patch: ${{ steps.version.outputs.patch }}"
          echo "isRelease: ${{ steps.version.outputs.isRelease }}"
