name: Docker Build with Autoversion

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for autoversion

      - name: run stuff
        run: |
          printenv
          git branch -a
          git fetch
          git branch -a
          git checkout main

      - name: Calculate version
        id: version
        uses: trondhindenes/autoversion@v1.0.22

